[options]
admin_passwd = $pbkdf2-sha512$600000$DqEUQgiBcI7x/l8rZcy5tw$C9zLyzmI2316SQI/HdThlKCD1i7Gsyyw1xuxIrIzbjhmweaghyEv8VboacOSypG/p9f/vKjmiwHfTKqTHlJYxQ
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = False
http_port = 8011
log_level = info
logfile = C:\Users\moh.kulaib\Desktop\odoo\odoo.log
addons_path = C:\Users\moh.kulaib\Desktop\odoo\addons,C:\Users\moh.kulaib\Desktop\odoo\odoo\addons
data_dir = C:\Users\moh.kulaib\Desktop\odoo\session
xmlrpc_port = 8017

